version: '3'
services:
  web:
    build:
      context: .      
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 6000M
    volumes:
      # - /app/node_modules
      - .:/app
      - ./nginx/certs/goDaddy:/etc/ssl/certs
      - ./nginx.conf:/etc/nginx/conf.d/default.conf